# Generated by Django 5.1.3 on 2024-11-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarbonEmission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='sub_category',
            field=models.CharField(default='default_sub_category', help_text='Subcategory of activity (e.g., car, electricity)', max_length=50),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='category',
            field=models.CharField(default='default_category', help_text='Category of activity (e.g., transport, buildings)', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='emissionfactor',
            unique_together={('category', 'sub_category')},
        ),
    ]
