# Generated by Django 5.1.3 on 2024-11-11 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarbonEmission', '0002_useractivity_sub_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='date',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='unit',
            field=models.CharField(default='km', max_length=50),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='category',
            field=models.CharField(choices=[('transport', 'Transportation'), ('buildings', 'Buildings'), ('industry', 'Industry')], max_length=100),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='sub_category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
