# Generated by Django 5.1.3 on 2024-11-11 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarbonEmission', '0003_remove_useractivity_date_useractivity_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='category',
            field=models.CharField(choices=[('Transport', 'Transportation'), ('Buildings', 'Buildings'), ('Industry', 'Industry')], max_length=100),
        ),
    ]
