# Generated by Django 5.1.3 on 2024-11-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarbonEmission', '0004_alter_useractivity_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='unit',
            field=models.CharField(default='KM', max_length=50),
        ),
    ]
