# Generated by Django 5.1.3 on 2024-12-01 18:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarbonEmission', '0008_alter_passwordresettoken_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'category', 'sub_category'], name='CarbonEmiss_user_id_3d1072_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['date'], name='CarbonEmiss_date_fb417f_idx'),
        ),
        migrations.AddConstraint(
            model_name='useractivity',
            constraint=models.UniqueConstraint(fields=('user', 'category', 'sub_category', 'date'), name='unique_user_activity'),
        ),
    ]
