# Generated by Django 5.1.3 on 2024-12-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarbonEmission', '0009_useractivity_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoryEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('sub_category', models.CharField(max_length=50)),
                ('effect_title', models.CharField(max_length=100)),
                ('effect_description', models.TextField()),
            ],
            options={
                'unique_together': {('category', 'sub_category', 'effect_title')},
            },
        ),
        migrations.CreateModel(
            name='SubCategorySolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('sub_category', models.CharField(max_length=50)),
                ('solution_title', models.CharField(max_length=100)),
                ('solution_description', models.TextField()),
            ],
            options={
                'unique_together': {('category', 'sub_category', 'solution_title')},
            },
        ),
    ]
